spring:
  jpa:
    database: ORACLE
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.Oracle10gDialect
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:XE
    username: admin_vista
    password: admin_vista123